config/routes.rb
Rails.application.routes.draw do
  resources :contents 
  post 'search' => 'contents#search'
  devise_for :users

  root 'contents#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  belongs_to :user
  validates :image,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
  has_attached_file :image, styles: {
    big: '600x400>',
    medium: '300x200>',
    mini: '75x50>'
  }
  validates :name, presence: true
  validates :content_type, inclusion: { in: %w(image video link),
    message: "%{value} is not a valid type" }
  def to_param
    self.slug
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_content, only: [:edit, :update, :destroy]
  # GET /contents
  # GET /contents.json
  def index
    if current_user == nil
      @contents = Content.where(published: true).all
    else
      @contents = Content.where("published = ? OR user_id = ?", true, current_user.id).all
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find_by(slug: params[:id])
    redirect_to '/422.html' if not @content.published and (current_user == nil or current_user.id != @content.user_id)
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def search
    if current_user == nil
      @contents = Content.where("published = ? and name like ? ", true, "%#{params[:text_searched]}%") .all
    else
      @contents = Content.where("(published = ? OR user_id = ?) and name like ? ", true, current_user.id, "%#{params[:text_searched]}%").all
    end
    render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find_by(slug: params[:id])
      redirect_to '/422.html' unless @content.user_id == current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:name, :content_type, :content, :image, :slug, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= select("content", "content_type", %w[image video link], {prompt: 'Select a type'}) %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to media contents</h1>
<%= form_tag(search_path) do %>
   <%= text_field_tag('text_searched') %>
   <%= button_tag("Search") %>
<% end %> 
<% if @contents.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Content type</th>
        <th>Content</th>
        <th>Image</th>
        <th>Slug</th>
        <th>Published</th>
        <th>User</th>    
        <th colspan="3"></th>
      
      </tr>
    </thead>

    <tbody>
      <% @contents.each do |content| %>
        <tr>
          <td><%= content.name %></td>
          <td><%= content.content_type %></td>
          <% if content.content_type == 'image' %>
          <td><%= content.content %></td>
          <td><%= image_tag content.image :mini %></td>
          <% else %>
            <td><%= content.content.html_safe %></td>
            <td>-</td>
          <% end %>
          <td><%= content.content %></td>
          <td><%= content.image %></td>
          <td><%= content.slug %></td>
          <td><%= content.published %></td>
          <td><%= content.user.email %></td>
          <td><%= link_to 'Show', content %></td>
          <% if user_signed_in? and current_user.id == content.user_id %>

            <td><%= link_to 'Edit', edit_content_path(content) %></td>
            <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td>-</td>
            <td>-</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @content.content_type %>
</p>


<% if @content.content_type == 'image' %>
  <p>
    <strong>Content:</strong>
    <%= @content.content %>
  </p>
  <p>
    <strong>Image:</strong>
    <%= image_tag @content.image :medium %>
  </p>
<% else %>
  <p>
    <strong>Content:</strong>
    <%= @content.content.html_safe %>
  </p>
<% end %>
<p>
  <strong>Slug:</strong>
  <%= @content.slug %>
</p>



<p>
  <strong>User:</strong>
  <%= @content.user.email %>
</p>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_content_path(@content) %> |
<% end %>
<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediacontent</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<%= yield %>

</body>
</html>